name: Build and test
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches: [ develop ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build API
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./TaktTusur.Media.Api/Dockerfile
          push: false
          platforms: "linux/amd64"
      - name: Build Background Worker
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./TaktTusur.Media.Worker/Dockerfile
          push: false
          platforms: "linux/amd64"
